language: python
python:
- '3.5'
- '3.5-dev'
- 'nightly'
install: make init
script: make test
deploy:
  provider: heroku
  api_key:
    secure: bMTNw2AegPSaD6aGLObO+AVNn/UIPYp+IWWl9QaHK5AlnCMENICOzn3N/6dj0bOD+uCysriT1ZP7TyCoceEFe7w8P+XLD2ThU6PG9sPmb3yzqOYEkHDOuf6eYt2LETv1jPPJDRaeB3c82oLfz10yqF7LV+ryiqRA9Q/Nw5yaKYLjzAwuclGdL70LvM4JTNKASFOM/U9ONlJS7jwvYlxEgZ3PcRD8BJUadnbMCVL/KE+A+xyfVB161BAZ8KYz4jtMVlC+r0TsVISKHt+3/zG8DA6l1mnu9xBI43lgMwSexZBjZfjacocVswqL/0QtZkBy/9RlwgVCSwvFlscWxSpzGMmwEXSs5Vp9oAJ/nnTZHyixSZqJj1I57lUAd21RzNIg6C0jt7pOk72ne17bjwYYaWbxPWvvoCgOlE1KBAwn5rUywzWsy+xcpGKeewf+jbKB55+ppIlQt3bQkmQHfYzIthdcxJUjOrUu4OYhWN5lxBdfs0N/o5JP2Z10HTWXENVBzwtIJvLo6twhzNKKGkpvVfXtM7oKMOSHhziwiuCa3yP5SnwPBMOPMYYQ2bJOjkCcbV5TlIhmK8LyXcSQXJcQsNfKBZWk/P/qQ7W/UKBMlPbezs07qJBCJuUWX2kIW6vGwxtjSBKvKxPEHfUJ+/7o6O/7j2FOnY+VOrw87SMSAvc=
  app:
    master: zoho-timesheet
    dev: zoho-timesheet-dev
  on:
      python: '3.5'
notifications:
  email: false
